// <auto-generated />
namespace GS.Trade.TimeSeries.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class BarVolume : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BarVolume));
        
        string IMigrationMetadata.Id
        {
            get { return "201405031007171_Bar.Volume"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
