//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace GS.Trade.DB.TickModel.FT1203
{
    public partial class Category
    {
        public Category()
        {
            this.Symbols = new HashSet<Symbol>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Symbol> Symbols { get; set; }
    }
    
}
