//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace GS.Trade.DB.TickModel.FT1203
{
    public partial class M1203 : DbContext
    {
        public M1203()
            : base("name=M1203")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Categories { get; set; }
        public DbSet<Series> Series { get; set; }
        public DbSet<SeriesDef> SeriesDefs { get; set; }
        public DbSet<SeriesPart> SeriesParts { get; set; }
        public DbSet<Symbol> Symbols { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Ticker> Tickers { get; set; }
        public DbSet<TickerStore> TickerStores { get; set; }
        public DbSet<Tick> Ticks { get; set; }
        public DbSet<TimeInt> TimeInts { get; set; }
    }
}
