//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace GS.Trade.DB.TickModel.FT1203
{
    public partial class SeriesPart
    {
        public int ID { get; set; }
        public int SeriesDefID { get; set; }
        public int TickerID { get; set; }
        public System.DateTime DT1 { get; set; }
        public System.DateTime DT2 { get; set; }
    
        public virtual SeriesDef SeriesDef { get; set; }
        public virtual Ticker Ticker { get; set; }
    }
    
}
