//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace GS.Trade.DB.TickModel.FT1203
{
    public partial class Symbol
    {
        public Symbol()
        {
            this.Tickers = new HashSet<Ticker>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string LongCode { get; set; }
        public int CategoryID { get; set; }
        public byte Enabled { get; set; }
        public Nullable<short> TickerDays { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Ticker> Tickers { get; set; }
    }
    
}
