//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace GS.Trade.DB.TickModel.FT1203
{
    public partial class Tick
    {
        public long ID { get; set; }
        public int SeriesID { get; set; }
        public System.DateTime DT { get; set; }
        public double Price { get; set; }
        public int Amount { get; set; }
    
        public virtual Series Series { get; set; }
    }
    
}
