//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace GS.Trade.DB.TickModel.FT1203
{
    public partial class Ticker
    {
        public Ticker()
        {
            this.Series = new HashSet<Series>();
            this.SeriesParts = new HashSet<SeriesPart>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string LongCode { get; set; }
        public string KeyCode { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DT1 { get; set; }
        public Nullable<System.DateTime> DT2 { get; set; }
        public Nullable<System.DateTime> D1 { get; set; }
        public Nullable<System.DateTime> D2 { get; set; }
        public Nullable<System.DateTime> D3 { get; set; }
        public Nullable<int> Cnt { get; set; }
        public string Alias { get; set; }
        public int SymbolID { get; set; }
    
        public virtual ICollection<Series> Series { get; set; }
        public virtual ICollection<SeriesPart> SeriesParts { get; set; }
        public virtual Symbol Symbol { get; set; }
    }
    
}
