//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace GS.Trade.DB.TickModel.FT1203
{
    public partial class TimeInt
    {
        public TimeInt()
        {
            this.Series = new HashSet<Series>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte Enabled { get; set; }
    
        public virtual ICollection<Series> Series { get; set; }
    }
    
}
